import Head from 'next/head';
import styled from "styled-components";
import Nav from 'comp/Nav';
import Hero from 'comp/Hero';
import styles from '@/styles/Home.module.css';
import { useEffect, useState, useContext,useCallback } from "react";
import { useTheme } from "@/utils/provider";
import {bg} from "@/utils/variables";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

const MainStructure = styled.div`
display:flex;
flex-direction:row;
background:${(props)=> props.bg};
padding:0 40px;
width:100vw;
`
const Main = styled.div`
display: flex;
flex-direction: column;
padding:1.0rem;
min-height: 100vh;
background:${(props)=>props.bg};
width:100%;
`



const Home =() =>{
  const [color, setColor] = useState(true);
  const { theme, setTheme } = useTheme();
  const { t } = useTranslation('common');


  const onChangeColor = () => {
  
    if(color === false){
      setTheme(theme === "dark" ? "light":"dark");
      setColor(true);
    }else if(color === true){
      setTheme(theme === "dark" ? "light":"dark");
      setColor(false);
    }
  };

  return (
    <>
      <Head>
        <title>Chisaki Nakamura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_header.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Noto+Sans+TC:wght@100..900&display=swap" rel="stylesheet"/>
      </Head>
      <Nav handleColor={()=>onChangeColor()} fm={t('FontFamily.Content')}/>
      <Hero fm={t('FontFamily.Header')} parafm={t('FontFamily.Content')} heading={t('Hero.MyName')} content={t('Hero.Content')} text_content={t('Hero.Button_text')} Btnfm={t('FontFamily.Content')}/>
      <MainStructure bg={bg[theme]}>
      {/*---------------------------- Main Contents From Here ---------------------------*/}
      <Main>
      <div id="about"><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        About me
        </div>
      <div id="works"><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        Works</div>
      <div id="contact"><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        contact</div>
        <br/><br/><br/><br/><br/><br/><br/>
      </Main>
      {/*---------------------------- Main Contents Finish Here ---------------------------*/}

      </MainStructure>
    </>
  )
}
export const getServerSideProps = async ({ locale }) => ({
  props: {
      ...(await serverSideTranslations(locale, ['common'], null, ['en','zh-Hant','ja'])),
  },
}); 
export default Home;